# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20170516_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='amazon_category',
            new_name='rakuten_category',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='amazon_url',
            new_name='rakuten_url',
        ),
    ]
